import type { Question } from "./types"
import { v4 as uuidv4 } from "uuid"

export const dummyQuestions: Question[] = [
  // Round 1 Questions (5 questions per team pair)
  {
    id: uuidv4(),
    question: "Name something people do to relax after a stressful day",
    answers: [
      { text: "Take a bath", points: 30 },
      { text: "Watch TV", points: 25 },
      { text: "Read a book", points: 20 },
      { text: "Exercise", points: 15 },
      { text: "Listen to music", points: 10 },
      { text: "Have a drink", points: 8 },
      { text: "Meditate", points: 5 },
      { text: "Call a friend", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name a food that people often eat too much of at a buffet",
    answers: [
      { text: "Desserts", points: 35 },
      { text: "Pizza", points: 25 },
      { text: "Fried chicken", points: 20 },
      { text: "Pasta", points: 15 },
      { text: "Seafood", points: 10 },
      { text: "Salad", points: 8 },
      { text: "Bread", points: 5 },
      { text: "Fruit", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something you might find in a hotel room",
    answers: [
      { text: "Bed", points: 40 },
      { text: "TV", points: 30 },
      { text: "Bible", points: 20 },
      { text: "Mini fridge", points: 15 },
      { text: "Coffee maker", points: 10 },
      { text: "Hair dryer", points: 8 },
      { text: "Iron", points: 5 },
      { text: "Safe", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name a reason why someone might be late for work",
    answers: [
      { text: "Traffic", points: 35 },
      { text: "Overslept", points: 30 },
      { text: "Car trouble", points: 20 },
      { text: "Public transport delay", points: 15 },
      { text: "Weather", points: 10 },
      { text: "Kids", points: 8 },
      { text: "Lost keys", points: 5 },
      { text: "Forgot something", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something people do while waiting in line",
    answers: [
      { text: "Check phone", points: 40 },
      { text: "Talk to others", points: 25 },
      { text: "People watch", points: 15 },
      { text: "Check the time", points: 10 },
      { text: "Fidget", points: 8 },
      { text: "Read", points: 7 },
      { text: "Listen to music", points: 5 },
      { text: "Complain", points: 3 },
    ],
  },
  // Additional Round 1 Questions
  {
    id: uuidv4(),
    question: "Name a place where people take selfies",
    answers: [
      { text: "Tourist attractions", points: 35 },
      { text: "Beach", points: 25 },
      { text: "Bathroom mirror", points: 20 },
      { text: "Restaurants", points: 15 },
      { text: "Concerts", points: 10 },
      { text: "Gym", points: 8 },
      { text: "Car", points: 5 },
      { text: "Work", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something people collect as a hobby",
    answers: [
      { text: "Stamps", points: 30 },
      { text: "Coins", points: 25 },
      { text: "Action figures", points: 20 },
      { text: "Trading cards", points: 15 },
      { text: "Vinyl records", points: 10 },
      { text: "Books", points: 8 },
      { text: "Shoes", points: 5 },
      { text: "Antiques", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something people do to prepare for a job interview",
    answers: [
      { text: "Research the company", points: 35 },
      { text: "Practice answers", points: 30 },
      { text: "Pick outfit", points: 20 },
      { text: "Update resume", points: 15 },
      { text: "Haircut", points: 10 },
      { text: "Get directions", points: 8 },
      { text: "Sleep early", points: 5 },
      { text: "Prepare questions", points: 3 },
    ],
  },
  // Round 2 Questions (2 questions per team pair)
  {
    id: uuidv4(),
    question: "Name a reason why someone might cancel plans with a friend",
    answers: [
      { text: "Sick", points: 35 },
      { text: "Too tired", points: 25 },
      { text: "Work emergency", points: 20 },
      { text: "Family obligation", points: 15 },
      { text: "Better offer", points: 10 },
      { text: "No money", points: 8 },
      { text: "Bad weather", points: 5 },
      { text: "Forgot", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something people complain about at restaurants",
    answers: [
      { text: "Slow service", points: 35 },
      { text: "Food quality", points: 30 },
      { text: "Prices", points: 20 },
      { text: "Temperature", points: 15 },
      { text: "Noise level", points: 10 },
      { text: "Portion size", points: 8 },
      { text: "Cleanliness", points: 5 },
      { text: "Seating", points: 3 },
    ],
  },
  // Additional Round 2 Questions
  {
    id: uuidv4(),
    question: "Name something people do to save money",
    answers: [
      { text: "Cook at home", points: 35 },
      { text: "Use coupons", points: 25 },
      { text: "Buy on sale", points: 20 },
      { text: "Cancel subscriptions", points: 15 },
      { text: "Thrift shopping", points: 10 },
      { text: "DIY repairs", points: 8 },
      { text: "Carpool", points: 5 },
      { text: "Budget planning", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name a reason why someone might get a new phone",
    answers: [
      { text: "Old one broke", points: 40 },
      { text: "Upgrade features", points: 30 },
      { text: "Contract renewal", points: 15 },
      { text: "Battery issues", points: 10 },
      { text: "Lost previous one", points: 8 },
      { text: "Gift", points: 7 },
      { text: "Status symbol", points: 5 },
      { text: "Work requirement", points: 3 },
    ],
  },
  // Round 3 Questions (3 questions per team pair)
  {
    id: uuidv4(),
    question: "Name something people do on their lunch break",
    answers: [
      { text: "Eat", points: 40 },
      { text: "Scroll social media", points: 25 },
      { text: "Run errands", points: 15 },
      { text: "Take a walk", points: 10 },
      { text: "Nap", points: 8 },
      { text: "Socialize", points: 7 },
      { text: "Work more", points: 5 },
      { text: "Read", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name a common New Year's resolution",
    answers: [
      { text: "Lose weight", points: 35 },
      { text: "Exercise more", points: 30 },
      { text: "Save money", points: 20 },
      { text: "Quit smoking", points: 15 },
      { text: "Learn something new", points: 10 },
      { text: "Travel more", points: 8 },
      { text: "Reduce stress", points: 5 },
      { text: "Volunteer", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something people do to prepare for a vacation",
    answers: [
      { text: "Pack luggage", points: 35 },
      { text: "Book accommodations", points: 30 },
      { text: "Research activities", points: 20 },
      { text: "Exchange currency", points: 15 },
      { text: "Stop mail", points: 10 },
      { text: "Pet arrangements", points: 8 },
      { text: "Set out-of-office", points: 5 },
      { text: "Check weather", points: 3 },
    ],
  },
  // Additional Round 3 Questions
  {
    id: uuidv4(),
    question: "Name something people typically forget to pack for a trip",
    answers: [
      { text: "Toothbrush", points: 35 },
      { text: "Phone charger", points: 30 },
      { text: "Medications", points: 25 },
      { text: "Underwear", points: 20 },
      { text: "Sunscreen", points: 15 },
      { text: "Passport/ID", points: 10 },
      { text: "Swimsuit", points: 5 },
      { text: "Hairbrush", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name a popular street food",
    answers: [
      { text: "Hot dogs", points: 35 },
      { text: "Tacos", points: 30 },
      { text: "Pizza", points: 25 },
      { text: "Pretzels", points: 20 },
      { text: "Ice cream", points: 15 },
      { text: "Kebabs", points: 10 },
      { text: "Corn on the cob", points: 5 },
      { text: "Crepes", points: 3 },
    ],
  },
  {
    id: uuidv4(),
    question: "Name something people do when they can't sleep",
    answers: [
      { text: "Watch TV", points: 35 },
      { text: "Read a book", points: 30 },
      { text: "Count sheep", points: 25 },
      { text: "Check phone", points: 20 },
      { text: "Take a walk", points: 15 },
      { text: "Drink water", points: 10 },
      { text: "Meditate", points: 5 },
      { text: "Take medicine", points: 3 },
    ],
  },
]

// Extra questions for tiebreakers or additional rounds
export const extraQuestions: Question[] = dummyQuestions.slice(15, 25)

